### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by silverbullettruck2001** [saibotsivad/bpr-npm-audit#8]
I tried adding a step in my bitbucket pipeline using this, but I am getting an error when it runs.

Here's the step I added:
```
            - step:
                name: 'NPM Audit Check'
                script:
                  - npx bpr-npm-audit
```

here's the error I am getting when it builds:
```
+ npx bpr-npm-audit
npx: installed 1 in 1.815s
Unexpected token U in JSON at position 1
```

Can you tell me what I am doing wrong?
